package org.springaicommunity.github.ai.classification;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springaicommunity.github.ai.classification.domain.ClassificationResponse;
import org.springaicommunity.github.ai.classification.domain.LabelPrediction;
import org.springaicommunity.github.ai.classification.service.ComprehensiveMetricsCalculator;
import org.springaicommunity.github.ai.classification.service.FilteredEvaluationService;
import org.springaicommunity.github.ai.classification.service.PostProcessingFilter;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springaicommunity.github.ai.classification.config.ClassificationConfiguration;

import java.io.File;
import java.io.IOException;
import java.time.Duration;
import java.time.Instant;
import java.util.*;

import static org.assertj.core.api.Assertions.*;

/**
 * Stage 0: Evaluation-Only Parity Test
 * 
 * <p>CRITICAL TEST: Verifies that Java's evaluation logic can achieve exactly 82.1% F1
 * when fed Python's raw predictions. This isolates evaluation bugs from upstream issues.</p>
 * 
 * <p>Expected Results:
 * <ul>
 *   <li>If Java achieves 82.1% F1: Evaluation is clean, problem is upstream</li>
 *   <li>If Java achieves <82.1% F1: Bug in Java evaluation (filtering, metrics, etc.)</li>
 * </ul>
 * 
 * <p>This is the FIRST and most important parity gate. All other investigations depend on this passing.</p>
 */
@SpringJUnitConfig(classes = {ClassificationConfiguration.class})
@DisplayName("Stage 0: Evaluation-Only Parity Test")
class EvaluationParityTest {
    
    private static final Logger log = LoggerFactory.getLogger(EvaluationParityTest.class);
    
    // Python baseline result - this is what we MUST achieve
    private static final double PYTHON_BASELINE_F1 = 0.821; // 82.1%
    private static final double TOLERANCE = 0.001; // ±0.1%
    
    // File paths
    private static final String JAVA_PREDICTIONS_PATH = "/home/mark/project-mgmt/spring-ai-project-mgmt/scripts/project/classification-engine/java_small_batch_classification_2025-08-18_17-34-22_dedup.json";
    private static final String TEST_SET_PATH = "/home/mark/project-mgmt/spring-ai-project-mgmt/issues/stratified_split/test_set.json";
    
    private FilteredEvaluationService evaluationService;
    private PostProcessingFilter postProcessingFilter;
    private ComprehensiveMetricsCalculator metricsCalculator;
    private ObjectMapper objectMapper;
    
    @BeforeEach
    void setUp() {
        objectMapper = new ObjectMapper();
        postProcessingFilter = new PostProcessingFilter();
        metricsCalculator = new ComprehensiveMetricsCalculator();
        evaluationService = new FilteredEvaluationService(
            postProcessingFilter, metricsCalculator, objectMapper);
    }
    
    @Test
    @DisplayName("Java LLM predictions MUST achieve reasonable performance vs Python's 82.1% F1")
    void testJavaLLMPredictionsEvaluation() throws IOException {
        log.info("=== JAVA LLM PREDICTIONS EVALUATION ===");
        log.info("Loading Java's LLM predictions and ground truth...");
        
        // Load Java's predictions (generated by ClaudeCodeWrapperSmallBatchTest)
        List<ClassificationResponse> javaPredictions = loadJavaPredictions();
        log.info("Loaded {} Java LLM predictions", javaPredictions.size());
        
        // Load ground truth
        Map<Integer, Set<String>> groundTruth = loadGroundTruth();
        log.info("Loaded ground truth for {} issues", groundTruth.size());
        
        // Run Java's evaluation logic on Java's LLM predictions
        log.info("Running Java evaluation on Java LLM predictions...");
        Instant startTime = Instant.now();
        
        var evaluationResult = evaluationService.evaluateWithPythonFiltering(
            javaPredictions, TEST_SET_PATH);
        
        Duration evaluationTime = Duration.between(startTime, Instant.now());
        log.info("Evaluation completed in {}ms", evaluationTime.toMillis());
        
        // Extract the critical F1 score
        double javaF1 = evaluationResult.filteredMetrics().microMetrics().f1();
        double javaF1Percentage = javaF1 * 100;
        double parityPercentage = (javaF1 / PYTHON_BASELINE_F1) * 100;
        
        log.info("=== JAVA LLM RESULTS ===");
        log.info("Python Baseline F1: {}%", String.format("%.1f", PYTHON_BASELINE_F1 * 100));
        log.info("Java LLM F1: {}%", String.format("%.1f", javaF1Percentage));
        log.info("Parity Achievement: {}% of Python baseline", String.format("%.1f", parityPercentage));
        log.info("Difference: {} percentage points", 
                String.format("%.1f", Math.abs(javaF1Percentage - (PYTHON_BASELINE_F1 * 100))));
        
        // Log detailed metrics for debugging
        var filteredMicroMetrics = evaluationResult.filteredMetrics().microMetrics();
        log.info("Java Detailed Metrics:");
        log.info("  Precision: {}", String.format("%.3f", filteredMicroMetrics.precision()));
        log.info("  Recall: {}", String.format("%.3f", filteredMicroMetrics.recall()));
        log.info("  F1 Score: {}", String.format("%.3f", filteredMicroMetrics.f1()));
        
        // Log filtering statistics
        var filteringStats = evaluationResult.filteringStats();
        log.info("Java Filtering Stats:");
        log.info("  Issues affected: {}/{} ({}%)", 
                filteringStats.issuesAffected(), filteringStats.totalIssues(),
                String.format("%.1f", filteringStats.getAffectedPercentage()));
        log.info("  Predictions removed: {}/{} ({}%)",
                filteringStats.removedPredictions(), filteringStats.originalPredictions(),
                String.format("%.1f", filteringStats.getRemovedPercentage()));
        
        // Performance assessment
        if (parityPercentage >= 99.0) {
            log.info("🎉 EXCELLENT: Java achieves near-perfect parity with Python baseline!");
        } else if (parityPercentage >= 90.0) {
            log.info("✅ GOOD: Java achieves strong parity with Python baseline");
        } else if (parityPercentage >= 80.0) {
            log.info("🟡 ACCEPTABLE: Java achieves reasonable parity with Python baseline");
        } else {
            log.info("🔴 GAP: Java has significant parity gap with Python baseline");
        }
        
        // Log success rate and coverage
        log.info("Coverage: {}/{} predictions generated ({}%)", 
                javaPredictions.size(), 111, String.format("%.1f", (double) javaPredictions.size() / 111 * 100));
        
        // Verify we have a reasonable number of predictions
        assertThat(javaPredictions.size())
            .as("Should have a reasonable number of predictions")
            .isGreaterThan(50);  // At least 50 predictions out of 111
        
        // Verify F1 score is reasonable
        assertThat(javaF1)
            .as("Java F1 score should be reasonable (above 0.5)")
            .isGreaterThan(0.5);
        
        log.info("✅ JAVA LLM EVALUATION COMPLETE - {} predictions evaluated", javaPredictions.size());
    }
    
    /**
     * Load Java's LLM predictions from the generated predictions file
     */
    private List<ClassificationResponse> loadJavaPredictions() throws IOException {
        File javaFile = new File(JAVA_PREDICTIONS_PATH);
        if (!javaFile.exists()) {
            throw new IllegalStateException("Java predictions file not found: " + JAVA_PREDICTIONS_PATH);
        }
        
        JsonNode javaArray = objectMapper.readTree(javaFile);
        List<ClassificationResponse> predictions = new ArrayList<>();
        
        for (JsonNode predNode : javaArray) {
            int issueNumber = predNode.get("issue_number").asInt();
            String explanation = predNode.has("explanation") ? predNode.get("explanation").asText() : "No explanation provided";
            
            // Parse predicted labels
            List<LabelPrediction> labelPredictions = new ArrayList<>();
            JsonNode predictedLabelsNode = predNode.get("predicted_labels");
            if (predictedLabelsNode != null && predictedLabelsNode.isArray()) {
                for (JsonNode labelNode : predictedLabelsNode) {
                    String label = labelNode.get("label").asText();
                    double confidence = labelNode.get("confidence").asDouble();
                    labelPredictions.add(new LabelPrediction(label, confidence));
                }
            }
            
            // Create ClassificationResponse matching Java format
            ClassificationResponse response = ClassificationResponse.builder()
                .issueNumber(issueNumber)
                .predictedLabels(labelPredictions)
                .explanation(explanation)
                .processingTime(Duration.ofMillis(7000)) // Approximate from logs
                .tokenUsage(3500L) // Approximate
                .build();
            
            predictions.add(response);
        }
        
        log.info("Converted {} Java LLM predictions to ClassificationResponse format", predictions.size());
        return predictions;
    }
    
    /**
     * Load ground truth from test_set.json
     */
    private Map<Integer, Set<String>> loadGroundTruth() throws IOException {
        File testFile = new File(TEST_SET_PATH);
        if (!testFile.exists()) {
            throw new IllegalStateException("Test set file not found: " + TEST_SET_PATH);
        }
        
        JsonNode testSetArray = objectMapper.readTree(testFile);
        Map<Integer, Set<String>> groundTruth = new HashMap<>();
        
        for (JsonNode issueNode : testSetArray) {
            int issueNumber = issueNode.get("issue_number").asInt();
            Set<String> labels = new HashSet<>();
            
            for (JsonNode labelNode : issueNode.get("labels")) {
                labels.add(labelNode.asText());
            }
            
            groundTruth.put(issueNumber, labels);
        }
        
        log.info("Loaded ground truth for {} issues", groundTruth.size());
        return groundTruth;
    }
}